name: Update README

on:
  push:
    branches:
      - master

jobs:
  updateContributors:
    runs-on: ubuntu-latest
    container: node:12-alpine3.11
    steps:
      - run: apk add bash git python3 py3-pip
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Update README 
        run: |
          echo "{ \"repository\":\"${repository}\" }" > package.json
          npx contributor-faces . --exclude '(*github*)|(*dependabot*)'
          rm package.json
          git add README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: update contributors
          title: Update contributors
          body: Credit new contributors to README.md
          branch: update-contributors
          token: ${{ secrets.GITHUB_TOKEN }}


